name: YouTube Telegram Stats

on:
  schedule:
    - cron: "0 * * * *"   # каждый час
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачать репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Установить Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Установить библиотеки
      - name: Install dependencies
        run: pip install requests

      # 4. Запуск скрипта
      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python bot.py
